apiVersion: apps/v1
kind: Deployment 
metadata: # ici les metadata lié au Deployment 
  # Nom de l’objet, il doit être unique dans le namespace
  name: deployment-example
  namespace: default
spec: # Ici les spécifications du Deployment
  # Lance 2 Pods 
  replicas: 2
 selector:
    matchLabels:
      app: nginx
  template:
    metadata: # ici les metadata lié aux Pods (ne pas confondre avec les précédents) 
      labels:
        app: nginx
    spec: # Ici les spécifications des Pods
      containers: # un Pod peut contenir plusieurs conteneurs
      - name: web
        image: nginx:1.18.0