apiVersion: v1
kind: Pod
metadata:
  name: web-color
spec:
  containers:
    - name: web-color
      image: mmumshad/simple-webapp-color
      ports:
        - name: web-color
          containerPort: 8080
          protocol: TCP
       
      env:  
        - name: APP_COLOR
          value: red
