apiVersion: v1
kind: Service
metadata:
  name: myfirstservice-color
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008
    name: http
  selector:
    app: web



