apiVersion: v1
kind: Pod
metadata:
  name: web-color-blue
  labels:
    app: web
spec:
  containers:
    - name: web-color-blue
      image: mmumshad/simple-webapp-color
      ports:
        - name: web-color
          containerPort: 8080
          protocol: TCP

      env:
        - name: APP_COLOR
          value: blue

