apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec: 
  containers:
  - image: mysql
    name: mysql
    volumeMounts: 
    - mountPath: /var/lib/mysql
      name: data-mysql
    env: 
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: sahib-kube
      - name: MYSQL_USER
        value: easy
      - name: MYSQL_PASSWORD
        value: easy
  volumes:
  - name: data-mysql
    hostPath:
      path: "/data"
      type: Directory



























